### ISSUE TITLE
Unable to change smoothing level in `response` GUI

### ISSUE THREAD

**Issue by tkillestein** [jkrogager/PyNOT#26]
Thanks for the really useful package!

When running `spex` with `interactive=True` set for the `response` step, it's not possible to change the smoothing factor that appears in the GUI from the default of 0.02. 

* It doesn't seem to inherit the value set in the `options_spex.yml` config file.
* The backspace key doesn't clear the value, unless I Ctrl/Cmd-A, but then the GUI won't let me write anything but integer values in.

I'm running on v1.3.4, and changing the smoothing value works fine in non-interactive mode (i.e. the correct value appears in the logs.

**Comment by jkrogager** [comment]
Thanks for catching this! There seems to be an error in the GUI validator that verifies that the input is indeed a floating point number... Not sure where this came from. This should be fixed in the next version. If you want, you can pull the updated code from the branch mentioned in the pull-request above.
