### ISSUE TITLE
Feature request: Storing sky spectrum in the output file

### ISSUE THREAD

**Issue by steveschulze** [jkrogager/PyNOT#4]
Hi JK,

Would it be possible to store the proper sky spectrum in the output file? The skylines could be used to finetune the wavelength calibration either by the user or even within PyNOT.

Cheers,

Steve

**Comment by jkrogager** [comment]
I just made a quick update so you can turn off the automated sky-subtraction. You then have to fit the background as part of the extraction step (where you can also save the 2D sky-subtracted image if you need that). Note: skipping the automated sky-subtraction might affect cosmic ray detection and correction (if near bright skylines), so you might have to turn this step off (by setting niter=0). This is the best I could do for now. I'll try to see if I can implement something more self-consistent where the automated sky subtraction gets passed to the extraction in order to generate a proper 1d sky spectrum.
Ultimately, the 2D skymodel is saved in the 2D sky-sub FITS file (extension=SKY), so you can manually extract the 1d from there as well.
